include:
  - project: infrastructure/kubernetes-flux
    ref: main
    file: .gitlab/include/CommitToBranch.gitlab-ci.yaml

stages:
  - validate
  - build
  - deploy

.script_auth_kaniko: &script_auth_kaniko
  - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

validate-frontend:
  stage: validate
  needs: [ ]
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/timbru31/java-node:17-jre-16
  script:
    - cd apps/webnet-builder-frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - apps/webnet-builder-frontend/dist/webnet-builder-frontend

build-frontend-image:
  stage: build
  needs: [ validate-frontend ]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - *script_auth_kaniko
    - /kaniko/executor
      --context $CI_PROJECT_DIR/apps/webnet-builder-frontend
      --dockerfile $CI_PROJECT_DIR/apps/webnet-builder-frontend/Dockerfile
      --destination $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG
      --digest-file=$CI_PROJECT_DIR/image-digest
  artifacts:
    name: image-digest
    paths:
      - image-digest
    expire_in: never

.dev-environment:
  environment:
    name: dev
    url: https://webnet-builder-dev.main-kubernetes.wogra.com/
  when: manual

.main-environment:
  environment:
    name: main
    url: https://webnet-builder-main.main-kubernetes.wogra.com/
  only:
    - main

.commit-kubernetes-ressources:
  stage: deploy
  extends:
    - .commit-to-branch
  needs:
    - build-frontend-image
  allow_failure: true
  resource_group: git-branch-deploy
  script:
    - rm -rf $CI_ENVIRONMENT_SLUG
    - cp -R $CI_PROJECT_DIR/deploy $CI_ENVIRONMENT_SLUG
    - export FRONTEND_IMAGE_DIGEST=$(cat $CI_PROJECT_DIR/image-digest)
    - |
      cat <<EOF > $CI_ENVIRONMENT_SLUG/kustomization.yaml
      ---
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
      components:
        - env/$CI_ENVIRONMENT_SLUG
      commonLabels:
        app.kubernetes.io/instance: "webnet-builder-$CI_ENVIRONMENT_SLUG"
      images:
        - name: 'gitlab-registry.wogra.com/wogra-projects/thesis/neural-network-development-platform/frontend'
          newTag: $CI_COMMIT_REF_SLUG
          digest: $FRONTEND_IMAGE_DIGEST
      EOF
    - cat $CI_ENVIRONMENT_SLUG/kustomization.yaml
    - git add $CI_ENVIRONMENT_SLUG

deploy-k8s-dev:
  extends:
    - .commit-kubernetes-ressources
    - .dev-environment

deploy-k8s-main:
  extends:
    - .commit-kubernetes-ressources
    - .main-environment