---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/component: "frontend"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: "frontend"
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
